TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../../src/alu.sv tb.v # Update per module
TOPLEVEL = tb
MODULE = test_alu  # Python test filename without .py

include $(shell cocotb-config --makefiles)/Makefile.sim
